## Deployment
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-dev
spec:
  selector:
    matchLabels:
      app: app-dev
  replicas: 5 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
      - name: app-dev
        image: kserge2001/school:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
## Service
apiVersion: v1
kind: Service
metadata:
  name: app-dev-service
  labels:
    app: app-dev
spec:
  selector:
    app: app-dev
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
